### ISSUE TITLE
Not able to Create the case class for following json

### ISSUE THREAD

**Issue by amitprasadom** [julianpeeters/case-class-generator#3]
{"result":[[{"last24hrs":{"fiat":9050,"vol":500000,"difffiat":"-182835","diffvol":"-10000000"}}],[{"max24Hr":1810000,"diff":"-20000"}],[{"min24Hr":1810000,"diff":"70000"}],[{"lasttrade":[{"ask":[[{"rate":1810000,"volume":500000,"time":1437856586316}]]}]}],{"highestBid":1810000},{"lowestAsk":1850000},{"allaskCoinSum":319800000,"allbidFiatSum":6229412}]}

Please help to figureout

**Comment by julianpeeters** [comment]
Hi Amit,
This library is most useful in conjunction with a schema-parsing library, and even then the mapping one chooses is fairly arbitrary. If you'd like to share a little more about why you need case classes, and why you need to generate them at runtime, I'd be happy to help further.

I think you may be looking for [json2caseclass](http://json2caseclass.cleverapps.io/)

It will complain that your data can't be easily represented in Scala because the type that parameterizes the result field is heterogeneous:

pseudocode:
```scala
case class Result(result: List[List[Last24Hrs], List[Max24Hrs]...])
...
```

The best you can do without restructuring your data (or exploring Shapeless' HLists) is:

```scala
case class Result(result: List[Any])
...
```

**Comment by amitprasadom** [comment]
mate i have already used . but in current json they are some data without parent key . so there only i am getting problem . i will appreciate you much if you will create case class for above json .

**Comment by amitprasadom** [comment]
any way i used 
case class Ticker(result1:List[List[Last24Hrs],List[Max24HrChild],List[Min24HrChild],List[LastTradeMaster]]) 
giving me an error saying 
wrong number of type arguments for List, should be 1 
which is obvious

**Comment by julianpeeters** [comment]
yes, but that is how the your json is structured. 

You could try `case class Ticker(result: List[Any])`

Or else investigate how to use Shapeless' [Hlists](https://github.com/milessabin/shapeless/wiki/Feature-overview:-shapeless-2.0.0#heterogenous-lists)

**Comment by amitprasadom** [comment]
if i will use Any, how  would i pass the parameters as a case class in List

**Comment by julianpeeters** [comment]
Without using Shapeless, the best route would be to restructure your data. If that is not possible, then `Any` is top-level, so every case class is an `Any`. This loses a lot of type-safety, but it will compile. If you need, you can always cast using `.asInstanceOf[Last24Hrs]` for example.
